In [21]:
import pickle
import os
from datetime import datetime
import pandas as pd
import numpy as np

In [22]:
model_path = r"C:\Users\ASUS\Jupyter Proj\Seoul Bike Sharing Ind. Project\models\xgboost_regressor_r2_0_949_v1.pkl"
model = pickle.load(open(model_path, 'rb'))

In [23]:
data = [
    [ 1.07807977,  0.22192612,  0.77468297,  1.82005277, -1.26200749,
       -0.25194272, -0.12916836, -0.17535463, -0.22754885, -5.47803337,
       -0.64744078, -0.43640293,  0.30459857,  1.74132735, -0.58152447,
       -0.57866842, -0.40630934, -0.40916536, -0.4075004 ,  2.46842407,
       -0.40081071, -0.41367015],
    [-0.65432992,  1.24504573,  0.23697162, -0.5001855 ,  0.56154562,
       -0.28664608, -0.12916836, -0.17535463, -0.22754885,  0.18254726,
        0.94701966,  0.14260346,  0.30459857, -0.57427456,  1.71961809,
       -0.57866842, -0.40630934, -0.40916536, -0.4075004 , -0.40511677,
        2.49494334, -0.41367015]
]

prediction = model.predict(data)
list(prediction)

[223.20695, 1331.3179]

## Load SC

In [24]:
sc_dump_path = r"C:\Users\ASUS\Jupyter Proj\Seoul Bike Sharing Ind. Project\models\sc.pkl"

sc = pickle.load(open(sc_dump_path, "rb"))

In [25]:
sc

StandardScaler()

### User input

In [52]:
Date = "02/01/2025"
Hour = 18
Temperature = 29
Humidity = 25
Wind_speed = 3
Visibility = 90
Solar_Radiation = 5
Rainfall = 0
Snowfall = 0.0
Seasons = "Winter"
Holiday = "No Holiday"
Functioning_Day = "Yes"
city="Nagpur"

# import random
# Date = "15/07/2023"  # A random date in summer (mid-July)
# Hour = random.randint(6, 20)  # Random hour between 6 AM and 8 PM
# Temperature = random.randint(20, 35)  # Random temperature between 20°C and 35°C
# Humidity = random.randint(50, 100)  # Random humidity between 50% and 100%
# Wind_speed = random.randint(5, 70)  # Random wind speed between 5 km/h and 70 km/h
# Visibility = random.randint(5, 100)  # Random visibility between 5 km and 100 km
# Solar_Radiation = random.randint(50, 900)  # Random solar radiation (W/m²) between 50 and 900
# Rainfall = random.randint(0, 100)  # Random rainfall in mm (can be 0 for a dry day)
# Snowfall = 0.0  # No snow in July
# Seasons = "Summer"  # Random season in July (South Korea's summer season)
# Holiday = random.choice(["Holiday", "No Holiday"])  # Randomly choosing if it's a holiday or not
# Functioning_Day = random.choice(["Yes", "No"])

### Converting user data into model consumable format

In [40]:
from datetime import datetime


# Function to convert date string to a dictionary with day, month, year, and week day
def get_string_to_datetime(date):
    # Convert the string 'date' to a datetime object
    dt = datetime.strptime(date, "%d/%m/%Y")
    
    # Return a dictionary with the desired attributes
    return {
        "day": dt.day,
        "month": dt.month,
        "year": dt.year,
        "week_day": dt.strftime("%A")  # Day of the week as a string (e.g., 'Monday')
}

In [41]:
str_to_date = get_string_to_datetime(Date)
print(str_to_date)

holiday_dic = {"No Holiday":0, "Holiday":1}
functioning_day= {"No":0, "Yes":1}

{'day': 2, 'month': 1, 'year': 2025, 'week_day': 'Thursday'}

In [42]:
u_input_list = [Hour, Temperature, Humidity, Wind_speed, Visibility, Solar_Radiation, Rainfall, Snowfall,holiday_dic[Holiday],  functioning_day[Functioning_Day], str_to_date["day"], str_to_date["month"], str_to_date["year"] ]

features_name = ['Hour', 'Temperature(°C)', 'Humidity(%)',
       'Wind speed (m/s)', 'Visibility (10m)', 'Solar Radiation (MJ/m2)',
       'Rainfall(mm)', 'Snowfall (cm)', 'Holiday', 'Functioning Day', 'Day',
       'Month', 'Year']

u_input_list

[18, 29, 25, 3, 90, 5, 0, 0.0, 0, 1, 2, 1, 2025]

In [43]:
features_name

['Hour',
 'Temperature(°C)',
 'Humidity(%)',
 'Wind speed (m/s)',
 'Visibility (10m)',
 'Solar Radiation (MJ/m2)',
 'Rainfall(mm)',
 'Snowfall (cm)',
 'Holiday',
 'Functioning Day',
 'Day',
 'Month',
 'Year']

In [44]:
def seasons_to_df(Seasons):
    import numpy as np
    seasons_cols = ['Spring', 'Summer', 'Winter']
    seasons_data=np.zeros((1,len(seasons_cols)), dtype="int")
    df_seasons=pd.DataFrame(seasons_data, columns=seasons_cols)
    if(Seasons in seasons_cols):
        df_seasons[Seasons]=1
    return df_seasons
        
df_seasons = seasons_to_df(Seasons)

In [45]:
def day_df(week_day):
    days_names= ['Monday', 'Saturday', 'Sunday', 'Thursday', 'Tuesday', 'Wednesday']
    days_name_data = np.zeros((1,len(days_names)), dtype="int")

    df_days=pd.DataFrame(days_name_data, columns=days_names)

    if week_day in days_names:
        df_days[week_day]=1
    return df_days

df_days = day_df(str_to_date["week_day"])
df_days

   Monday  Saturday  Sunday  Thursday  Tuesday  Wednesday
0       0         0       0         1        0          0

In [46]:
df_u_input = pd.DataFrame([u_input_list], columns=features_name)
df_u_input

,Hour,Temperature(°C),Humidity(%),Wind speed (m/s),Visibility (10m),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Holiday,Functioning Day,Day,Month,Year
0,18,29,25,3,90,5,0,0.0,0,1,2,1,2025

In [47]:
['Hour', 'Temperature(°C)', 'Humidity(%)',
       'Wind speed (m/s)', 'Visibility (10m)', 'Solar Radiation (MJ/m2)',
       'Rainfall(mm)', 'Snowfall (cm)', 'Holiday', 'Functioning Day', 'Day',
       'Month', 'Year', 'Spring', 'Summer', 'Winter', 'Monday', 'Saturday',
       'Sunday', 'Thursday', 'Tuesday', 'Wednesday']

['Hour',
 'Temperature(°C)',
 'Humidity(%)',
 'Wind speed (m/s)',
 'Visibility (10m)',
 'Solar Radiation (MJ/m2)',
 'Rainfall(mm)',
 'Snowfall (cm)',
 'Holiday',
 'Functioning Day',
 'Day',
 'Month',
 'Year',
 'Spring',
 'Summer',
 'Winter',
 'Monday',
 'Saturday',
 'Sunday',
 'Thursday',
 'Tuesday',
 'Wednesday']

In [48]:
df_for_pred = pd.concat([df_u_input,df_seasons, df_days],axis=1)

In [49]:
df_for_pred

,Hour,Temperature(°C),Humidity(%),Wind speed (m/s),Visibility (10m),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Holiday,Functioning Day,...,Year,Spring,Summer,Winter,Monday,Saturday,Sunday,Thursday,Tuesday,Wednesday
0,18,29,25,3,90,5,0,0.0,0,1,...,2025,0,0,1,0,0,0,1,0,0

In [50]:
sc_data_for_pred = sc.transform(df_for_pred)
sc_data_for_pred

array([[ 0.93371229,  1.34486228, -1.6205767 ,  1.2399932 , -2.22654507,
         5.12707859, -0.12916836, -0.17535463, -0.22754885,  0.18254726,
        -1.55856103, -1.59441569, 25.41785495, -0.57427456, -0.58152447,
         1.72810536, -0.40630934, -0.40916536, -0.4075004 ,  2.46842407,
        -0.40081071, -0.41367015]])

### Prediction in deployment

In [53]:
model.predict(sc_data_for_pred)
print(f"Rented Bike Demand in city {city} on Date : {Date}, and Time : {Hour} is : {round(model.predict(sc_data_for_pred).tolist()[0])}")

Rented Bike Demand in city Nagpur on Date : 02/01/2025, and Time : 18 is : 1021